### ISSUE TITLE
Add LICENSE file to allow automatic detection of licenses in these jspm dependencies

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [jspm/nodelibs-assert#3]
we would like to be able to track automatically JSPM dependencies in our project, and are writing a JSMP plugin for the license_finder tool to be able to do so.

For the list of libraries below license_finder cannot detect the License that applies.

Would it be possible to add a LICENSE file, or add the license in a spec that makes the license to apply explicit?

jspm-nodelibs-assert, 0.2.0, unknown
jspm-nodelibs-buffer, 0.2.0, unknown
jspm-nodelibs-child_process, 0.2.0, unknown
jspm-nodelibs-constants, 0.2.0, unknown
jspm-nodelibs-crypto, 0.2.0, unknown
jspm-nodelibs-events, 0.2.0, unknown
jspm-nodelibs-fs, 0.2.0, unknown
jspm-nodelibs-http, 0.2.0, unknown
jspm-nodelibs-https, 0.2.1, unknown
jspm-nodelibs-module, 0.2.0, unknown
jspm-nodelibs-net, 0.2.0, unknown
jspm-nodelibs-os, 0.2.0, unknown
jspm-nodelibs-path, 0.2.1, unknown
jspm-nodelibs-process, 0.2.0, unknown
jspm-nodelibs-stream, 0.2.0, unknown
jspm-nodelibs-string_decoder, 0.2.0, unknown
jspm-nodelibs-tls, 0.2.0, unknown
jspm-nodelibs-tty, 0.2.0, unknown
jspm-nodelibs-url, 0.2.0, unknown
jspm-nodelibs-util, 0.2.1, unknown
jspm-nodelibs-vm, 0.2.0, unknown
jspm-nodelibs-zlib, 0.2.0, unknown

**Comment by guybedford** [comment]
@andrewdavidmackenzie certainly I'd be happy to update these, PR's here would be very welcome too. The libraries are all based on these implementations - https://github.com/substack/node-browserify#compatibility.

**Comment by andrewdavidmackenzie** [comment]
We can do PRs if you let me know which license you would like.

**Comment by guybedford** [comment]
That would be great. The original licenses are from the projects which are linked to from the list of original implementations at https://github.com/substack/node-browserify#compatibility. Let me know if you need help finding any of these.

**Comment by andrewdavidmackenzie** [comment]
Hmmmm.

That repo has a LICENSE file with Joyent, and Fair Oaks Labs, Inc. - copyright notices....

Not sure if I want to do a PR claiming their copyright - when I have no past knowledge of either of these repos...

**Comment by guybedford** [comment]
The repo is a direct fork so should retain those original licenses - these are from Node core implementations hence are Joyent licenses.

**Comment by andrewdavidmackenzie** [comment]
Legal advice alerts me to the statement at the end of the license (https://github.com/substack/node-browserify/blob/master/LICENSE) referring to contributions by "Brian White" who's copyright and license remain unclear.

**Comment by guybedford** [comment]
@andrewdavidmackenzie the licenses to follow are at the original repos from that list of core modules. Eg the first one is https://github.com/defunctzombie/commonjs-assert/blob/master/LICENSE/.

**Comment by andrewdavidmackenzie** [comment]
@guybedford checking with legal department on my side.... they tend to agree with me that it's better for me (the "consumer" of the libs) to not be adding the LICENSE file, but either the maintainer or the copyright holders. Sorry :-(

It would be great if they could be added into this repo, as from a legal standpoint, referring to the other repo doesn't really guarantee anything.... Ideally the license files would be distributed with the nspm packages and also identify the license in nspm registry.

**Comment by guybedford** [comment]
@andrewdavidmackenzie I'd be happy to take a PR that merges the correct license into this repo, and then to post a new release with it in due course. The thing is there are many repos like this one, so I just don't have the time to update them all at once manually that is all.

**Comment by andrewdavidmackenzie** [comment]
Hi Guy,

seems we're stuck on this one.

I work for Red Hat (will add the redhat org to my GH...) and we'd like to use these libraries in our project. However, we require red Hat Legal to review and approve the licenses of dependencies we use.

As neither a maintainer, nor contributor, to neither the original repo or this repo - they consider (and I agree) that I am in no position to assert what license should apply. That really needs to be done with knowledge of where the code came from, contributions made since they were cloned/forked (if any).

So, while I'd be happy to do the leg-work of creating PRs to get this solved, based on my (non-existant) role in this repo, it doesn't make sense for me to do so.

How to unblock the situation? I imagine there are others in a similar situation, who need a more explicit definition of the license that applies.

Makes sense?

**Comment by guybedford** [comment]
@andrewdavidmackenzie the license here is also included in the source code at https://github.com/jspm/nodelibs-assert/blob/master/assert.js. If I were to merge a PR providing the LICENSE here from yourself as a separate file, and publish it with this project, the act of my publishing the project with a new license is enough because of the act of publishing and merging in the first place. In addition this isn't a license change, but a license clarification of a license that is already clearly there. Also applying a code diff it is clear that the code in that file matches the code from the original file at https://github.com/defunctzombie/commonjs-assert/blob/master/assert.js which has been linked, so the full history is available.

As mentioned, I have no problem creating a LICENSE file for this project and publishing it, the issue is that there are 32 of these projects that would potentially need that work, and that is not a job I have the time to just do myself.

**Comment by andrewdavidmackenzie** [comment]
OK, let me do one and then if all OK, I can do them all.

**Comment by andrewdavidmackenzie** [comment]
PR
https://github.com/jspm/nodelibs-assert/pull/4
